# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven release-windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Configure build for x86
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86
        
    - name: Set up JDK 18
      uses: actions/setup-java@v2
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    
    - name: Download GmSSL release
      run: |
        Invoke-WebRequest -Uri "https://github.com/guanzhi/GmSSL/archive/refs/tags/v3.1.1.zip" -OutFile "GmSSL-v3.1.1.zip"

    - name: Extract GmSSL
      run: |
        Expand-Archive -Path "GmSSL-v3.1.1.zip" -DestinationPath "GmSSL"

    - name: Build GmSSL
      run: |
        cd GmSSL;
        cd GmSSL-3.1.1;
        mkdir build;
        cd build;
        cmake .. -G "NMake Makefiles" -DWIN32=ON;
        nmake ;
        nmake install;
        $env:PATH += ";C:\Program Files\GmSSL\bin";
        echo $env:PATH;
        gmssl version;

    - name: Build with Maven
      run: mvn clean install
      
    - name: Clean up
      if: always()
      run: |
        Remove-Item -Recurse -Force GmSSLjava-version: '18'
        Remove-Item GmSSL-v3.1.1.zip
