name: maven-ci-release-ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 18
      uses: actions/setup-java@v2
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential
    
    - name: Download GmSSL release
      run: wget "https://github.com/guanzhi/GmSSL/archive/refs/tags/v3.1.1.zip" -O "GmSSL.zip"

    - name: Extract GmSSL
      run: unzip GmSSL.zip
    
    - name: Build GmSSL 
      run: |
        cd GmSSL-3.1.1
        mkdir build
        cd build
        cmake ..
        make
        sudo make install
        sudo ldconfig
        
    - name: Verify Installation and Environment
      run: gmssl version

    - name: Build with Maven
      run: mvn clean install
      
    - name: Clean up
      if: always()
      run: rm GmSSL.zip
