# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Maven CI-macos
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 18
      uses: actions/setup-java@v2
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
        
    - name: Build GmSSL
      run : |
        git clone https://github.com/guanzhi/GmSSL.git
        cd GmSSL
        mkdir build
        cd build
        cmake .. -DCMAKE_OSX_ARCHITECTURES=x86_64
        make
        sudo make install
    
    - name: Set DYLD_LIBRARY_PATH
      run: echo "DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
    
    - name: Build with Maven
      run: sudo mvn -B  -X  package --file pom.xml
